apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://172.30.1.2:6443
    insecure-skip-tls-verify: true
users:
- name: sandeep
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Il9zQ3RMM2JKNGZvQmtuTllyV2JEQm9ldHltaG5WbGRsa2REbjl6OFF1WncifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzUzMjUyNjIzLCJpYXQiOj
contexts:
- name: sandeep-context
  context:
    cluster: my-cluster
    user: sandeep
current-context: sandeep-context
